package com.example.expenselogger.data.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

@Entity(
    tableName = "expenses",
    foreignKeys = [
        ForeignKey(
            entity = CategoryEntity::class,
            parentColumns = ["id"],
            childColumns = ["categoryId"]
        ),
        ForeignKey(
            entity = RawTransactionEntity::class,
            parentColumns = ["id"],
            childColumns = ["rawTransactionId"]
        )
    ]
)
data class ExpenseEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val amount: Double,
    val categoryId: Int?,
    val merchantId: Int?,
    val description: String?,
    val transactionDate: Long,
    val source: String,
    val isAutoGenerated: Boolean,
    val userCorrected: Boolean,
    val rawTransactionId: Int?,
    val confidenceScore: Double
)
