package com.example.expenselogger.util

import android.content.Context
import com.example.expenselogger.data.entity.ExpenseEntity
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

object ExportUtils {

    fun exportExpensesToCSV(
        context: Context,
        expenses: List<ExpenseEntity>
    ): File {
        val file = File(context.filesDir, "expenses.csv")

        file.bufferedWriter().use { writer ->
            writer.write(
                "id,amount,categoryId,merchantId,description,transactionDate,source,isAutoGenerated,userCorrected,rawTransactionId\n"
            )

            expenses.forEach { e ->
                writer.write(
                    "${e.id}," +
                            "${e.amount}," +
                            "${e.categoryId ?: ""}," +
                            "${e.merchantId ?: ""}," +
                            "\"${e.description ?: ""}\"," +
                            "${e.transactionDate}," +
                            "${e.source}," +
                            "${e.isAutoGenerated}," +
                            "${e.userCorrected}," +
                            "${e.rawTransactionId ?: ""}\n"
                )
            }
        }

        return file
    }

    fun exportExpensesToJSON(
        context: Context,
        expenses: List<ExpenseEntity>
    ): File {
        val jsonArray = JSONArray()

        expenses.forEach { e ->
            val obj = JSONObject()
            obj.put("id", e.id)
            obj.put("amount", e.amount)
            obj.put("categoryId", e.categoryId)
            obj.put("merchantId", e.merchantId)
            obj.put("description", e.description)
            obj.put("transactionDate", e.transactionDate)
            obj.put("source", e.source)
            obj.put("isAutoGenerated", e.isAutoGenerated)
            obj.put("userCorrected", e.userCorrected)
            obj.put("rawTransactionId", e.rawTransactionId)
            jsonArray.put(obj)
        }

        val file = File(context.filesDir, "expenses.json")
        file.writeText(jsonArray.toString(2))
        return file
    }
}
