package com.example.expenselogger.util

import com.example.expenselogger.data.entity.ExpenseEntity
import org.json.JSONObject

object MlExportMapper {

    fun toTrainingSample(expense: ExpenseEntity): JSONObject {
        val obj = JSONObject()

        obj.put("amount", expense.amount)
        obj.put("description", expense.description)
        obj.put("categoryId", expense.categoryId)
        obj.put("confidence", expense.confidenceScore)
        obj.put("user_corrected", expense.userCorrected)
        obj.put("auto_generated", expense.isAutoGenerated)

        return obj
    }
}
