package com.example.expenselogger.ui.screen

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.expenselogger.data.entity.ExpenseEntity
import com.example.expenselogger.ui.viewmodel.ExpenseViewModel

@Composable
fun AddExpenseScreen(
    viewModel: ExpenseViewModel,
    onDone: () -> Unit
) {
    var amountText by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {

        Text("Add Expense", style = MaterialTheme.typography.headlineSmall)

        OutlinedTextField(
            value = amountText,
            onValueChange = { amountText = it },
            label = { Text("Amount") }
        )

        OutlinedTextField(
            value = description,
            onValueChange = { description = it },
            label = { Text("Description") }
        )

        Button(
            modifier = Modifier.fillMaxWidth(),
            onClick = {
                val amount = amountText.toDoubleOrNull() ?: return@Button

                viewModel.addExpense(
                    ExpenseEntity(
                        amount = amount,
                        categoryId = null,
                        merchantId = null,
                        description = description,
                        transactionDate = System.currentTimeMillis(),
                        source = "MANUAL",
                        isAutoGenerated = false,
                        userCorrected = false,
                        rawTransactionId = null,
                        confidenceScore = 1.0
                    )
                )

                onDone()
            }
        ) {
            Text("Save")
        }
    }
}
