package com.example.expenselogger.ui.screen

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.expenselogger.ui.viewmodel.AnalyticsViewModel

@Composable
fun AnalyticsScreen(
    viewModel: AnalyticsViewModel
) {
    val categorySummary by viewModel.categorySummary
    val summary by viewModel.summary

    LaunchedEffect(Unit) {
        viewModel.loadAnalytics()
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {

        Text("Analytics", style = MaterialTheme.typography.headlineMedium)

        Card {
            Column(Modifier.padding(12.dp)) {
                Text("Total Spend: ₹${summary.totalSpend}")
                Text("Auto-generated: ${summary.autoGeneratedCount}")
                Text("User corrected: ${summary.userCorrectedCount}")
            }
        }

        Text("Category-wise Spend", style = MaterialTheme.typography.titleMedium)

        LazyColumn(
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            items(categorySummary) { item ->
                Card {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(12.dp),
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Text(item.categoryName)
                        Text("₹${item.totalAmount}")
                    }
                }
            }
        }
    }
}
