package com.example.expenselogger.ui.viewmodel

import androidx.compose.runtime.State
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.expenselogger.data.AppDatabase
import kotlinx.coroutines.launch

data class CategorySummary(
    val categoryName: String,
    val totalAmount: Double
)

data class AnalyticsSummary(
    val totalSpend: Double,
    val autoGeneratedCount: Int,
    val userCorrectedCount: Int
)

class AnalyticsViewModel(
    private val db: AppDatabase
) : ViewModel() {

    private val _categorySummary =
        mutableStateOf<List<CategorySummary>>(emptyList())
    val categorySummary: State<List<CategorySummary>> = _categorySummary

    private val _summary =
        mutableStateOf(AnalyticsSummary(0.0, 0, 0))
    val summary: State<AnalyticsSummary> = _summary

    fun loadAnalytics() {
        viewModelScope.launch {
            val expenses = db.expenseDao().getAllExpenses()
            val categories = db.categoryDao().getAllCategories()

            val categoryMap = categories.associateBy { it.id }

            val grouped = expenses.groupBy { it.categoryId }

            _categorySummary.value = grouped.mapNotNull { (catId, list) ->
                val name = categoryMap[catId]?.name ?: return@mapNotNull null
                CategorySummary(
                    categoryName = name,
                    totalAmount = list.sumOf { it.amount }
                )
            }

            _summary.value = AnalyticsSummary(
                totalSpend = expenses.sumOf { it.amount },
                autoGeneratedCount = expenses.count { it.isAutoGenerated },
                userCorrectedCount = expenses.count { it.userCorrected }
            )
        }
    }
}
