package com.example.expenselogger.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.expenselogger.data.AppDatabase
import com.example.expenselogger.data.entity.ExpenseEntity
import com.example.expenselogger.util.ConfidenceScorer
import kotlinx.coroutines.launch

class ExpenseDraftViewModel(
    private val db: AppDatabase
) : ViewModel() {

    fun confirmDraft(
        rawTransactionId: Int,
        amount: Double,
        originalAmount: Double?,
        description: String?,
        categoryId: Int?
    ) {
        viewModelScope.launch {

            val userCorrected = originalAmount != amount

            val confidence = ConfidenceScorer.score(
                amountParsed = originalAmount != null,
                merchantParsed = description != null
            )

            val expense = ExpenseEntity(
                amount = amount,
                categoryId = categoryId,
                merchantId = null,
                description = description,
                transactionDate = System.currentTimeMillis(),
                source = "PHONEPE",
                isAutoGenerated = true,
                userCorrected = userCorrected,
                rawTransactionId = rawTransactionId,
                confidenceScore = confidence
            )

            db.expenseDao().insert(expense)
        }
    }
}
